backend:
  name: git-gateway
  branch: creditcard-mortgage
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:


  - name: "creditCards"
    label: "Credit Card"
    folder: "src/markdown/creditcards"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "credit-card-post"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Card Image", name: "cardImage", widget: image, required: true}
      - {label: "Credit Score", name: "creditScore", widget: "select", options: ["Excellent", "Good", "Fair", "Bad"], required: true}
      - {label: "Fee", name: "fee", widget: "number", required: true}
      - {label: "First Year Fee", name: "firstYearFee", widget: "number", required: false}
      - {label: "Bank Name", name: "bankName", widget: "string", required: false}
      - {label: "Network", name: "network", widget: "select", options: ["mastercard","visa"], required: false}
      - {label: "Purchase Interest", name: "purchaseInterest", widget: "number", required: false}
      - {label: "Balance Transfer Interest", name: "balanceTransferInterest", widget: "number", required: false}
      - {label: "Cash Advance Interest", name: "cashAdvanceInterest", widget: "number", required: false}
      - {label: "Balance Transfer Fee", name: "balanceTranferFees", widget: "number", required: false}
      - {label: "User Category", name: "userCategory", widget: "select", options: [{value: "personal", label: "Personal"}, {value: "student", label: "Student"}, {value: "business", label: "Business"}], required: true}
      - {label: "Card Category", required: true, name: "cardCategory", widget: "select", options: [{value: "low-interest", label: "Low Interest"}, {value: "low-balance-transfer", label: "Low Balance Transfer"}, {value: "build-credit-score", label: "Build Credit Score"}, {value: "prepaid", label: "Prepaid"}, {value: "rewards", label: "Rewards"}]}
      - {label: "External Site Link", name: "href", widget: "string", required: true}
      - {label: "Is it sponsered?", name: "sponsered", widget: "boolean", required: false}
      - {label: "Rating", name: "rating", widget: "select", options: ["0","1", "2", "3", "4", "5"], required: false}
      - {label: "Minimum Required Income", name: "minIncome", widget: "number", required: true}
      - {label: "Summary Description", name: "summaryDescription", widget: "markdown", required: false}
      - {label: "Is Featured?", name: "featured", widget: "boolean", required: false}

  
  - name: "homeBuyingMortgages"
    label: "Home Buying Mortgages"
    folder: "src/markdown/mortgages/homebanking"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-mortgages"}
      - {label: "mortgage", name: "mortgage", widget: "hidden", default: "mortgage"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Logo", name: "logo", widget: image, required: true}
      - {label: "Amortization", name: "amortization", widget: "select", default: "25", options: [{value: "5", label: "5 years"}, {value: "10", label: "10 years"}, {value: "15", label: "15 years"}, {value: "20", label: "20 years"}, {value: "25", label: "25 years"}, {value: "30", label: "30 years"}], required: true}
      - {label: "Is Featured?", name: "isFeatured", widget: "boolean", required: true}
      - {label: Insured (>20%dp), name: insured, widget: object, 
        fields: [
        {label: "1 year", name: "1", widget: string, required: true}, 
        {label: 2 years, name: "2", widget: string, required: true}, 
        {label: 3 years, name: "3", widget: string, required: true}, 
        {label: 4 years, name: "4", widget: string, required: true}, 
        {label: 5 years, name: "5", widget: string, required: true}, 
        ]
      }
      - {label: Uninsured 80% (<20%), name: uninsured, widget: object, 
        fields: [
        {label: "1 year", name: "1", widget: string, required: true}, 
        {label: 2 years, name: "2", widget: string, required: true}, 
        {label: 3 years, name: "3", widget: string, required: true}, 
        {label: 4 years, name: "4", widget: string, required: true}, 
        {label: 5 years, name: "5", widget: string, required: true}, 
        ]
      }

  - name: "refinancingMortgages"
    label: "Refinancing and Renewal Mortgages"
    folder: "src/markdown/mortgages/refinance"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "refinance-mortgages"}
      - {label: "mortgage", name: "mortgage", widget: "hidden", default: "mortgage"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Logo", name: "logo", widget: image, required: true}
      - {label: "Amortization", name: "amortization", widget: "select", default: "25", options: [{value: "5", label: "5 years"}, {value: "10", label: "10 years"}, {value: "15", label: "15 years"}, {value: "20", label: "20 years"}, {value: "25", label: "25 years"}, {value: "30", label: "30 years"}], required: true}
      - {label: "Is Featured?", name: "isFeatured", widget: "boolean", required: false}
      - {label: Rates, name: rates, widget: object, 
        fields: [
        {label: "1 year", name: "1", widget: string, required: true}, 
        {label: 2 years, name: "2", widget: string, required: true}, 
        {label: 3 years, name: "3", widget: string, required: true}, 
        {label: 4 years, name: "4", widget: string, required: true}, 
        {label: 5 years, name: "5", widget: string, required: true}, 
        ]
      }



  - name: "blog"
    label: "Blog"
    folder: "src/markdown/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "select", default: "blog", options: [{value: "credit card", label: "Credit Cards"}, {value: "mortgage", label: "Mortgage"}, {value: "blog", label: "Blog"}, {value: "insurance", label: "Insurance"}, {value: "banking", label: "Banking"}], required: true}


  - name: "knowledgehub"
    label: "Knowledge Hub"
    folder: "src/markdown/knowledgehub"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "knowledgehub-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Index", name: "index", widget: "number", required: true}
      - {label: "Category", name: "category", widget: "select", default: "blog", options: [{value: "credit-card", label: "Credit Cards"}, {value: "mortgage", label: "Mortgage"}, {value: "blog", label: "Blog"}, {value: "insurance", label: "Insurance"}, {value: "banking", label: "Banking"}], required: true}


  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}

  - name: "terms"
    label: "Terms of Service"
    folder: "src/markdown/terms"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "terms"}
      - {label: Title, name: title, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "privacy"
    label: "Privacy Policy"
    folder: "src/markdown/policy"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "privacy-policy"}
      - {label: Title, name: title, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "careers"
    label: "Careers"
    folder: "src/markdown/careers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careers"}
      - {label: Title, name: title, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}